extends RefCounted
## Declarative definitions for every Showcase Room.
##
## Each room is regenerated into rooms/showcase/<name>.tscn by
## tools/generate_showcase_rooms.gd. The map is a 16x9 grid of 16px cells
## ('#' = one block.tscn instance); things are placed on cells and converted
## to pixel positions by the generator. Giraffes authored above their resting
## cell fall and settle there, which keeps the definitions honest about what
## physics does.

# Entity keys:
#   player  {cell}                          Warma spawn (stands in the cell)
#   door    {cell, target}                  exit door, target = room name or res:// path
#   giraffe {cell, name}                    giraffe instance
#   button  {cell, name, target}            pressure plate embedded in a '#' cell
#   lift    {dir, cell|pos, name, min, max, speed, starts_extended, button}
#   pickup  {cell}                          extinguisher pickup
#   sign    {cell, text}                    signboard with a hint

const CATEGORY_INDEXES := {
	"FOUNDATION": "foundation_index",
	"GIRAFFE": "giraffe_index",
	"ELEVATOR": "elevator_index",
	"COMBINATIONS": "combinations_index",
	"MULTI": "multi_index",
	"TORTURE": "torture_index",
	"CHALLENGE": "challenge_index",
}

const ROOMS: Array[Dictionary] = [
	# ---------------------------------------------------------------- FOUNDATION
	{
		"name": "fnd_movement", "category": "FOUNDATION",
		"entry": "FOUNDATION · 移动与跳跃",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			".............##.",
			"..........#####.",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(2, 7)},
			{"type": "sign", "cell": Vector2i(4, 7), "text": "A/D 移动 · J 轻点小跳 长按大跳"},
			{"type": "door", "cell": Vector2i(14, 5), "target": "foundation_index"},
		],
	},
	{
		"name": "fnd_precision", "category": "FOUNDATION",
		"entry": "FOUNDATION · 精准平台",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"..............#.",
			"...........##...",
			".......##.......",
			"................",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(2, 7)},
			{"type": "sign", "cell": Vector2i(3, 7), "text": "部分脚在边缘上也算支撑 一样能起跳"},
			{"type": "door", "cell": Vector2i(14, 3), "target": "foundation_index"},
		],
	},
	{
		"name": "fnd_wall_jump", "category": "FOUNDATION",
		"entry": "FOUNDATION · 贴墙起跳",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"........#.......",
			"........#.......",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(2, 7)},
			{"type": "sign", "cell": Vector2i(5, 7), "text": "贴着墙起跳 不会穿墙也不会被卡住"},
			{"type": "door", "cell": Vector2i(13, 7), "target": "foundation_index"},
		],
	},
	{
		"name": "fnd_button", "category": "FOUNDATION",
		"entry": "FOUNDATION · 压力板与电梯",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"............##..",
			"............##..",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(2, 7)},
			{"type": "sign", "cell": Vector2i(4, 7), "text": "站上按钮电梯伸出 离开就缩回 趁早跳上去"},
			{"type": "button", "cell": Vector2i(7, 8), "name": "Btn1", "target": "Lift1"},
			{"type": "lift", "dir": "up", "cell": Vector2i(9, 8), "name": "Lift1", "min": 3.0, "max": 24.0, "speed": 12.0},
			{"type": "door", "cell": Vector2i(13, 5), "target": "foundation_index"},
		],
	},
	{
		"name": "fnd_music_bullet", "category": "FOUNDATION",
		"entry": "FOUNDATION · 灭火器与音符",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"............#...",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(2, 7)},
			{"type": "pickup", "cell": Vector2i(3, 7)},
			{"type": "sign", "cell": Vector2i(5, 7), "text": "K 发射音符 命中长颈鹿让它奔跑"},
			{"type": "giraffe", "cell": Vector2i(9, 7), "name": "Giraffe1"},
			{"type": "door", "cell": Vector2i(14, 7), "target": "foundation_index"},
		],
	},
	{
		"name": "fnd_death_reset", "category": "FOUNDATION",
		"entry": "FOUNDATION · 死亡与重置",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"##########...###",
		],
		"things": [
			{"type": "player", "cell": Vector2i(2, 7)},
			{"type": "sign", "cell": Vector2i(5, 7), "text": "掉下深坑 或按 R 都会重置本房间"},
			{"type": "door", "cell": Vector2i(14, 7), "target": "foundation_index"},
		],
	},
	# ------------------------------------------------------------------- GIRAFFE
	{
		"name": "fnd_giraffe_contact", "category": "GIRAFFE",
		"entry": "GIRAFFE · 基础接触",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(2, 7)},
			{"type": "sign", "cell": Vector2i(4, 7), "text": "侧面挡路 头顶可站 走开不会拖动它"},
			{"type": "giraffe", "cell": Vector2i(8, 7), "name": "Giraffe1"},
			{"type": "door", "cell": Vector2i(13, 7), "target": "giraffe_index"},
		],
	},
	{
		"name": "fnd_giraffe_stack", "category": "GIRAFFE",
		"entry": "GIRAFFE · 叠罗汉",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(2, 7)},
			{"type": "sign", "cell": Vector2i(4, 7), "text": "长颈鹿会叠成阶梯 逐级跳上去"},
			{"type": "giraffe", "cell": Vector2i(8, 7), "name": "Giraffe1"},
			{"type": "giraffe", "cell": Vector2i(8, 6), "name": "Giraffe2"},
			{"type": "giraffe", "cell": Vector2i(8, 4), "name": "Giraffe3"},
			{"type": "door", "cell": Vector2i(13, 7), "target": "giraffe_index"},
		],
	},
	{
		"name": "fnd_giraffe_bump", "category": "GIRAFFE",
		"entry": "GIRAFFE · 从下方顶起",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(8, 7)},
			{"type": "sign", "cell": Vector2i(4, 7), "text": "起跳把头顶的长颈鹿顶起来 它落回来还能再顶 R 可重置"},
			{"type": "giraffe", "cell": Vector2i(8, 6), "name": "Giraffe1"},
			{"type": "door", "cell": Vector2i(13, 7), "target": "giraffe_index"},
		],
	},
	# ------------------------------------------------------------------ ELEVATOR
	{
		"name": "elv_up", "category": "ELEVATOR",
		"entry": "ELEVATOR · 向上伸缩",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"...........##...",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(2, 7)},
			{"type": "sign", "cell": Vector2i(4, 7), "text": "左:踩按钮伸出 踢上去被载着降回 右:常伸电梯当平台"},
			{"type": "button", "cell": Vector2i(6, 8), "name": "Btn1", "target": "Lift1"},
			{"type": "lift", "dir": "up", "cell": Vector2i(8, 8), "name": "Lift1", "min": 3.0, "max": 24.0, "speed": 12.0},
			{"type": "lift", "dir": "up", "pos": Vector2(212, 128), "name": "Lift2", "min": 16.0, "max": 16.0, "starts_extended": true},
			{"type": "door", "cell": Vector2i(14, 7), "target": "elevator_index"},
		],
	},
	{
		"name": "elv_down", "category": "ELEVATOR",
		"entry": "ELEVATOR · 向下伸缩",
		"map": [
			"................",
			"................",
			".....###........",
			"................",
			"................",
			"................",
			"................",
			"................",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(2, 7)},
			{"type": "sign", "cell": Vector2i(3, 7), "text": "站到按钮上 向下的电梯会在吞掉你之前停下"},
			{"type": "button", "cell": Vector2i(6, 8), "name": "Btn1", "target": "Lift1"},
			{"type": "lift", "dir": "down", "cell": Vector2i(6, 2), "name": "Lift1", "min": 3.0, "max": 68.0, "speed": 16.0},
			{"type": "door", "cell": Vector2i(14, 7), "target": "elevator_index"},
		],
	},
	{
		"name": "elv_horizontal", "category": "ELEVATOR",
		"entry": "ELEVATOR · 水平伸缩",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"..............##",
			"###.....###..###",
			"###.....###..###",
			"###.....###..###",
			"###..........###",
		],
		"things": [
			{"type": "player", "cell": Vector2i(0, 4)},
			{"type": "sign", "cell": Vector2i(1, 4), "text": "两座常伸电梯桥 平面与砖块齐平 走过去"},
			{"type": "lift", "dir": "right", "pos": Vector2(48, 84.01), "name": "Bridge1", "min": 3.0, "max": 80.0, "starts_extended": true},
			{"type": "lift", "dir": "left", "pos": Vector2(208, 68.01), "name": "Bridge2", "min": 3.0, "max": 32.0, "starts_extended": true},
			{"type": "door", "cell": Vector2i(15, 3), "target": "elevator_index"},
		],
	},
	# -------------------------------------------------------------- COMBINATIONS
	{
		"name": "cmb_giraffe_elevator", "category": "COMBINATIONS",
		"entry": "COMBO · 长颈鹿压按钮",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"............##..",
			"............##..",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(2, 7)},
			{"type": "sign", "cell": Vector2i(3, 7), "text": "长颈鹿压住按钮 电梯就一直伸着"},
			{"type": "button", "cell": Vector2i(5, 8), "name": "Btn1", "target": "Lift1"},
			{"type": "giraffe", "cell": Vector2i(5, 7), "name": "Giraffe1"},
			{"type": "lift", "dir": "up", "cell": Vector2i(8, 8), "name": "Lift1", "min": 3.0, "max": 32.0, "speed": 16.0},
			{"type": "door", "cell": Vector2i(13, 5), "target": "combinations_index"},
		],
	},
	{
		"name": "cmb_bullet_plate", "category": "COMBINATIONS",
		"entry": "COMBO · 把长颈鹿赶上台",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"..............##",
			"..............##",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(1, 7)},
			{"type": "pickup", "cell": Vector2i(2, 7)},
			{"type": "sign", "cell": Vector2i(3, 7), "text": "用音符把长颈鹿赶到按钮上 别让它冲过头"},
			{"type": "giraffe", "cell": Vector2i(5, 7), "name": "Giraffe1"},
			{"type": "button", "cell": Vector2i(10, 8), "name": "Btn1", "target": "Lift1"},
			{"type": "lift", "dir": "up", "cell": Vector2i(13, 8), "name": "Lift1", "min": 3.0, "max": 32.0, "speed": 24.0},
			{"type": "door", "cell": Vector2i(15, 5), "target": "combinations_index"},
		],
	},
	{
		"name": "cmb_elevator_door", "category": "COMBINATIONS",
		"entry": "COMBO · 让电梯载着你上升",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"............###.",
			"................",
			"................",
			"................",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(1, 7)},
			{"type": "pickup", "cell": Vector2i(2, 7)},
			{"type": "sign", "cell": Vector2i(6, 7), "text": "先用音符把长颈鹿赶上按钮 趁电梯上升跳上去"},
			{"type": "giraffe", "cell": Vector2i(4, 7), "name": "Giraffe1"},
			{"type": "button", "cell": Vector2i(8, 8), "name": "Btn1", "target": "Lift1"},
			{"type": "lift", "dir": "up", "cell": Vector2i(10, 8), "name": "Lift1", "min": 3.0, "max": 48.0, "speed": 16.0},
			{"type": "door", "cell": Vector2i(13, 3), "target": "combinations_index"},
		],
	},
	{
		"name": "cmb_pickup_a", "category": "COMBINATIONS",
		"entry": "COMBO · 拾取与跨房间(起点)",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(2, 7)},
			{"type": "pickup", "cell": Vector2i(3, 7)},
			{"type": "sign", "cell": Vector2i(5, 7), "text": "拾取灭火器 然后走进门"},
			{"type": "door", "cell": Vector2i(13, 7), "target": "cmb_pickup_b"},
		],
	},
	{
		"name": "cmb_pickup_b", "category": "COMBINATIONS",
		"entry": "COMBO · 拾取与跨房间(终点)",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(2, 7)},
			{"type": "sign", "cell": Vector2i(4, 7), "text": "装备跟着你进来了吗? 按 K 试试"},
			{"type": "giraffe", "cell": Vector2i(8, 7), "name": "Giraffe1"},
			{"type": "door", "cell": Vector2i(13, 7), "target": "cmb_pickup_a"},
		],
	},
	{
		"name": "cmb_reset_giraffe", "category": "COMBINATIONS",
		"entry": "COMBO · 重置找回长颈鹿",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"##########...###",
		],
		"things": [
			{"type": "player", "cell": Vector2i(1, 7)},
			{"type": "pickup", "cell": Vector2i(2, 7)},
			{"type": "sign", "cell": Vector2i(4, 7), "text": "把长颈鹿射进深坑 再按 R 复原"},
			{"type": "giraffe", "cell": Vector2i(8, 7), "name": "Giraffe1"},
			{"type": "door", "cell": Vector2i(14, 7), "target": "combinations_index"},
		],
	},
	{
		"name": "cmb_reset_elevator", "category": "COMBINATIONS",
		"entry": "COMBO · 重置正在动的电梯",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(2, 7)},
			{"type": "sign", "cell": Vector2i(4, 7), "text": "电梯升到一半按 R 高度和位置都会复原"},
			{"type": "button", "cell": Vector2i(6, 8), "name": "Btn1", "target": "Lift1"},
			{"type": "lift", "dir": "up", "cell": Vector2i(8, 8), "name": "Lift1", "min": 3.0, "max": 40.0, "speed": 8.0},
			{"type": "door", "cell": Vector2i(13, 7), "target": "combinations_index"},
		],
	},
	# --------------------------------------------------------------------- MULTI
	{
		"name": "mlt_giraffe_logistics", "category": "MULTI",
		"entry": "MULTI · 长颈鹿物流线",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			".............##.",
			".............##.",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(1, 7)},
			{"type": "pickup", "cell": Vector2i(2, 7)},
			{"type": "sign", "cell": Vector2i(5, 7), "text": "让长颈鹿替你踩住按钮 再乘电梯上高台"},
			{"type": "giraffe", "cell": Vector2i(4, 7), "name": "Giraffe1"},
			{"type": "button", "cell": Vector2i(8, 8), "name": "Btn1", "target": "Lift1"},
			{"type": "lift", "dir": "up", "cell": Vector2i(10, 8), "name": "Lift1", "min": 3.0, "max": 32.0, "speed": 24.0},
			{"type": "door", "cell": Vector2i(14, 5), "target": "multi_index"},
		],
	},
	{
		"name": "mlt_stack_freight", "category": "MULTI",
		"entry": "MULTI · 电梯与叠塔",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"............####",
			"................",
			"................",
			"................",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(2, 7)},
			{"type": "sign", "cell": Vector2i(4, 7), "text": "电梯平台+长颈鹿=两级塔 跳上去"},
			{"type": "lift", "dir": "up", "cell": Vector2i(9, 8), "name": "Lift1", "min": 32.0, "max": 32.0, "starts_extended": true},
			{"type": "giraffe", "cell": Vector2i(9, 5), "name": "Giraffe1"},
			{"type": "door", "cell": Vector2i(14, 3), "target": "multi_index"},
		],
	},
	{
		"name": "mlt_elevator_relay", "category": "MULTI",
		"entry": "MULTI · 过桥接力",
		"map": [
			"................",
			"................",
			"................",
			"..............##",
			"..............##",
			"###......###..##",
			"###......###..##",
			"###......###..##",
			"###......###..##",
		],
		"things": [
			{"type": "player", "cell": Vector2i(0, 4)},
			{"type": "sign", "cell": Vector2i(1, 4), "text": "过桥 上电梯塔 跳上高塔进门"},
			{"type": "lift", "dir": "right", "pos": Vector2(48, 84.01), "name": "Bridge1", "min": 3.0, "max": 96.0, "starts_extended": true},
			{"type": "button", "cell": Vector2i(10, 5), "name": "Btn1", "target": "Lift1"},
			{"type": "giraffe", "cell": Vector2i(10, 4), "name": "Giraffe1"},
			{"type": "lift", "dir": "up", "cell": Vector2i(13, 8), "name": "Lift1", "min": 3.0, "max": 48.0, "speed": 16.0},
			{"type": "door", "cell": Vector2i(15, 2), "target": "multi_index"},
		],
	},
	# ------------------------------------------------------------------- TORTURE
	{
		"name": "trt_elevator", "category": "TORTURE",
		"entry": "TORTURE · 电梯压力场",
		"map": [
			"................",
			"................",
			".....###........",
			"................",
			"................",
			"................",
			".........#....#.",
			".........#....#.",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(0, 7)},
			{"type": "sign", "cell": Vector2i(1, 7), "text": "相邻双升同钮 不同速 下压会停在你头上 右侧两桥空中相接"},
			{"type": "button", "cell": Vector2i(1, 8), "name": "BtnA", "target": "LiftA"},
			{"type": "lift", "dir": "up", "pos": Vector2(40, 128), "name": "LiftA", "min": 3.0, "max": 40.0, "speed": 12.0, "button": "BtnA"},
			{"type": "lift", "dir": "up", "pos": Vector2(52, 128), "name": "LiftB", "min": 3.0, "max": 24.0, "speed": 48.0, "button": "BtnA"},
			{"type": "giraffe", "cell": Vector2i(2, 4), "name": "Giraffe1"},
			{"type": "button", "cell": Vector2i(6, 8), "name": "BtnC", "target": "LiftC"},
			{"type": "lift", "dir": "down", "cell": Vector2i(6, 2), "name": "LiftC", "min": 3.0, "max": 68.0, "speed": 16.0},
			{"type": "lift", "dir": "right", "pos": Vector2(160, 100.01), "name": "LiftD", "min": 3.0, "max": 32.0, "starts_extended": true},
			{"type": "lift", "dir": "left", "pos": Vector2(224, 100.01), "name": "LiftE", "min": 3.0, "max": 32.0, "starts_extended": true},
			{"type": "door", "cell": Vector2i(15, 7), "target": "torture_index"},
		],
	},
	{
		"name": "trt_giraffe", "category": "TORTURE",
		"entry": "TORTURE · 长颈鹿压力场",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"...........#....",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(0, 7)},
			{"type": "pickup", "cell": Vector2i(1, 7)},
			{"type": "sign", "cell": Vector2i(3, 7), "text": "射底层 驮者失撑掉落 台上长颈鹿当台阶 侧面挡路"},
			{"type": "giraffe", "cell": Vector2i(7, 7), "name": "Giraffe1"},
			{"type": "giraffe", "cell": Vector2i(7, 5), "name": "Giraffe2"},
			{"type": "giraffe", "cell": Vector2i(11, 6), "name": "Giraffe3"},
			{"type": "giraffe", "cell": Vector2i(13, 7), "name": "Giraffe4"},
			{"type": "door", "cell": Vector2i(15, 7), "target": "torture_index"},
		],
	},
	{
		"name": "trt_precision", "category": "TORTURE",
		"entry": "TORTURE · 精准压力场",
		"map": [
			"................",
			"................",
			"................",
			"......#.........",
			"......#......##.",
			"...........#....",
			"......#..#......",
			"......#.........",
			"################",
		],
		"things": [
			{"type": "player", "cell": Vector2i(2, 7)},
			{"type": "sign", "cell": Vector2i(3, 7), "text": "跳进墙缝 一格宽台阶 边缘起跳"},
			{"type": "door", "cell": Vector2i(14, 3), "target": "torture_index"},
		],
	},
	# ----------------------------------------------------------------- CHALLENGE
	{
		"name": "chl_musical_freight", "category": "CHALLENGE",
		"entry": "CHALLENGE · 音符货运",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"............####",
			"............####",
			"#########...####",
		],
		"things": [
			{"type": "player", "cell": Vector2i(1, 7)},
			{"type": "pickup", "cell": Vector2i(2, 7)},
			{"type": "sign", "cell": Vector2i(3, 7), "text": "赶长颈鹿上按钮 乘电梯 跃过深渊"},
			{"type": "giraffe", "cell": Vector2i(4, 7), "name": "Giraffe1"},
			{"type": "button", "cell": Vector2i(6, 8), "name": "Btn1", "target": "Lift1"},
			{"type": "lift", "dir": "up", "cell": Vector2i(7, 8), "name": "Lift1", "min": 3.0, "max": 32.0, "speed": 24.0},
			{"type": "door", "cell": Vector2i(14, 5), "target": "challenge_index"},
		],
	},
	{
		"name": "chl_vertical_climb", "category": "CHALLENGE",
		"entry": "CHALLENGE · 垂直攀爬",
		"map": [
			"................",
			"................",
			"................",
			"............####",
			"............####",
			".........#######",
			".......#.#######",
			".......#....####",
			"######..########",
		],
		"things": [
			{"type": "player", "cell": Vector2i(0, 7)},
			{"type": "sign", "cell": Vector2i(1, 7), "text": "电梯台+长颈鹿+深坑+阶梯塔 一路向上"},
			{"type": "lift", "dir": "up", "cell": Vector2i(3, 8), "name": "Lift1", "min": 32.0, "max": 32.0, "starts_extended": true},
			{"type": "giraffe", "cell": Vector2i(3, 5), "name": "Giraffe1"},
			{"type": "door", "cell": Vector2i(13, 2), "target": "challenge_index"},
		],
	},
]

# Navigation rooms: the hub and one index per category. Doors are placed in a
# row; each index also gets one return door to the hub.
const HUB_NAME := "showcase_hub"

const NAV_ROOMS: Array[Dictionary] = [
	{
		"name": HUB_NAME, "category": "HUB",
		"entry": "Showcase Hub · 站上门按 W 进入分类",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"################",
		],
		"doors": [
			{"cell": Vector2i(1, 7), "target": "foundation_index", "label": "基础"},
			{"cell": Vector2i(3, 7), "target": "giraffe_index", "label": "长颈鹿"},
			{"cell": Vector2i(5, 7), "target": "elevator_index", "label": "电梯"},
			{"cell": Vector2i(7, 7), "target": "combinations_index", "label": "组合"},
			{"cell": Vector2i(9, 7), "target": "multi_index", "label": "多机制"},
			{"cell": Vector2i(11, 7), "target": "torture_index", "label": "压力测试"},
			{"cell": Vector2i(13, 7), "target": "challenge_index", "label": "挑战"},
		],
	},
	{
		"name": "foundation_index", "category": "HUB",
		"entry": "FOUNDATION · 单机制示例",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"################",
		],
		"doors": [
			{"cell": Vector2i(1, 7), "target": "fnd_movement", "label": "移动跳跃"},
			{"cell": Vector2i(3, 7), "target": "fnd_precision", "label": "精准平台"},
			{"cell": Vector2i(5, 7), "target": "fnd_wall_jump", "label": "贴墙起跳"},
			{"cell": Vector2i(7, 7), "target": "fnd_button", "label": "压力板"},
			{"cell": Vector2i(9, 7), "target": "fnd_music_bullet", "label": "音符"},
			{"cell": Vector2i(11, 7), "target": "fnd_death_reset", "label": "死亡重置"},
			{"cell": Vector2i(14, 7), "target": HUB_NAME, "label": "返回"},
		],
	},
	{
		"name": "giraffe_index", "category": "HUB",
		"entry": "GIRAFFE · 单机制示例",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"################",
		],
		"doors": [
			{"cell": Vector2i(2, 7), "target": "fnd_giraffe_contact", "label": "接触"},
			{"cell": Vector2i(6, 7), "target": "fnd_giraffe_stack", "label": "叠罗汉"},
			{"cell": Vector2i(10, 7), "target": "fnd_giraffe_bump", "label": "顶起"},
			{"cell": Vector2i(14, 7), "target": HUB_NAME, "label": "返回"},
		],
	},
	{
		"name": "elevator_index", "category": "HUB",
		"entry": "ELEVATOR · 单机制示例",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"################",
		],
		"doors": [
			{"cell": Vector2i(2, 7), "target": "elv_up", "label": "向上"},
			{"cell": Vector2i(6, 7), "target": "elv_down", "label": "向下"},
			{"cell": Vector2i(10, 7), "target": "elv_horizontal", "label": "水平"},
			{"cell": Vector2i(14, 7), "target": HUB_NAME, "label": "返回"},
		],
	},
	{
		"name": "combinations_index", "category": "HUB",
		"entry": "COMBINATIONS · 双机制组合",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"################",
		],
		"doors": [
			{"cell": Vector2i(1, 7), "target": "cmb_giraffe_elevator", "label": "鹿压钮"},
			{"cell": Vector2i(3, 7), "target": "cmb_bullet_plate", "label": "赶鹿上台"},
			{"cell": Vector2i(5, 7), "target": "cmb_elevator_door", "label": "乘梯进门"},
			{"cell": Vector2i(7, 7), "target": "cmb_pickup_a", "label": "拾取跨房"},
			{"cell": Vector2i(9, 7), "target": "cmb_reset_giraffe", "label": "重置长颈鹿"},
			{"cell": Vector2i(11, 7), "target": "cmb_reset_elevator", "label": "重置电梯"},
			{"cell": Vector2i(14, 7), "target": HUB_NAME, "label": "返回"},
		],
	},
	{
		"name": "multi_index", "category": "HUB",
		"entry": "MULTI · 多机制互动",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"################",
		],
		"doors": [
			{"cell": Vector2i(2, 7), "target": "mlt_giraffe_logistics", "label": "物流线"},
			{"cell": Vector2i(6, 7), "target": "mlt_stack_freight", "label": "叠塔"},
			{"cell": Vector2i(10, 7), "target": "mlt_elevator_relay", "label": "双桥接力"},
			{"cell": Vector2i(14, 7), "target": HUB_NAME, "label": "返回"},
		],
	},
	{
		"name": "torture_index", "category": "HUB",
		"entry": "TORTURE · 物理压力测试",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"################",
		],
		"doors": [
			{"cell": Vector2i(2, 7), "target": "trt_elevator", "label": "电梯"},
			{"cell": Vector2i(6, 7), "target": "trt_giraffe", "label": "长颈鹿"},
			{"cell": Vector2i(10, 7), "target": "trt_precision", "label": "精准"},
			{"cell": Vector2i(14, 7), "target": HUB_NAME, "label": "返回"},
		],
	},
	{
		"name": "challenge_index", "category": "HUB",
		"entry": "CHALLENGE · 综合关卡",
		"map": [
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"................",
			"################",
		],
		"doors": [
			{"cell": Vector2i(4, 7), "target": "chl_musical_freight", "label": "音符货运"},
			{"cell": Vector2i(9, 7), "target": "chl_vertical_climb", "label": "垂直攀爬"},
			{"cell": Vector2i(14, 7), "target": HUB_NAME, "label": "返回"},
		],
	},
]

static func all_rooms() -> Array[Dictionary]:
	var result: Array[Dictionary] = []
	result.append_array(ROOMS)
	result.append_array(NAV_ROOMS)
	return result
